services:
  nfs-server:
    image: itsthenetwork/nfs-server-alpine:12
    container_name: nfs-server
    restart: unless-stopped
    privileged: true
    environment:
      - SHARED_DIRECTORY=/data
    volumes:
      - ./nfs_share:/data
    ports:
      - "111:111"
      - "2049:2049"
      - "20048:20048"
    networks:
      haproxy-net:
        ipv4_address: 192.168.2.100

  webserver1:
    image: nginx
    container_name: webserver1
    privileged: true
    networks:
      - haproxy-net
    depends_on:
      - nfs-server
    restart: always

  webserver2:
    image: nginx
    container_name: webserver2
    privileged: true
    networks:
      - haproxy-net
    depends_on:
      - nfs-server
    restart: always

  haproxy:
    image: haproxy:latest
    container_name: haproxy
    networks:
      - haproxy-net
    ports:
      - "80:80"
    volumes:
      - ./haproxy_config/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
      - webserver1
      - webserver2
    restart: always

networks:
  haproxy-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.2.0/24
