services:
  nfs-server:
    image: erichough/nfs-server
    container_name: nfs-server
    networks:
      - haproxy-net
    volumes:
      - ./nfs_share:/media
      - ./nfs_config/exports.txt:/etc/exports:ro
    cap_add:
      - SYS_ADMIN
    ports:
      - "2049:2049"
      - "2049:2049/udp"
      - "111:111"
      - "111:111/udp"
      - "32765:32765"
      - "32765:32765/udp"
      - "32767:32767"
      - "32767:32767/udp"
    restart: always

  webserver1:
    image: nginx
    container_name: webserver1
    networks:
      - haproxy-net
    volumes:
      - ./nfs_share:/usr/share/nginx/html
    depends_on:
      - nfs-server
    restart: always

  webserver2:
    image: nginx
    container_name: webserver2
    networks:
      - haproxy-net
    volumes:
      - ./nfs_share:/usr/share/nginx/html
    depends_on:
      - nfs-server
    restart: always

  haproxy:
    image: haproxy:latest
    container_name: haproxy
    networks:
      - haproxy-net
    ports:
      - "80:80"
    volumes:
      - ./haproxy_config/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
      - webserver1
      - webserver2
    restart: always

networks:
  haproxy-net:
    driver: bridge
